In [155]:
import numpy as np
import pandas as pd

In [156]:
credits=pd.read_csv("tmdb_5000_credits.csv")

In [157]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [158]:
movies=pd.read_csv("tmdb_5000_movies.csv")

In [159]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [160]:
credits.shape

(4803, 4)

In [161]:
movies = movies.head(2000)   # or 8000 max

In [162]:
movies.shape

(2000, 20)

In [163]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                2000 non-null   int64
 1   genres                2000 non-null   object
 2   homepage              864 non-null    object
 3   id                    2000 non-null   int64
 4   keywords              2000 non-null   object
 5   original_language     2000 non-null   object
 6   original_title        2000 non-null   object
 7   overview              2000 non-null   object
 8   popularity            2000 non-null   float64
 9   production_companies  2000 non-null   object
 10  production_countries  2000 non-null   object
 11  release_date          2000 non-null   object
 12  revenue               2000 non-null   int64
 13  runtime               2000 non-null   float64
 14  spoken_languages      2000 non-null   object
 15  status                2000 non-null   object
 16  tagline               1866 non-null   object
 17  title                 2000 non-null   object
 18  vote_average          2000 non-null   float64
 19  vote_count            2000 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 312.6+ KB

In [164]:
df=movies.merge(credits,on="title")

In [165]:
#essential columns for me now: 
#genres,id,keywords,overview,title

In [166]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [167]:
df.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [168]:
df=df[["movie_id","title","overview","genres","keywords","cast","crew"]]

In [169]:
df.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [170]:
df.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [171]:
df.dropna(inplace=True)

In [172]:
df.duplicated().sum()

0

In [173]:
df.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [174]:
df.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [175]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [176]:
df['genres']=df['genres'].apply(convert)

In [177]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [178]:
df['keywords']=df['keywords'].apply(convert)

In [179]:
#for cast
def convert2(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=5:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [180]:
df['cast']=df['cast'].apply(convert2)

In [181]:
#for crew
def convert3(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [182]:
df['crew']=df['crew'].apply(convert3)

In [183]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [184]:
df['overview']=df['overview'].apply(lambda x:x.split())

In [185]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [186]:
df['genres']=df['genres'].apply(lambda x:[i.replace(" ","") for i in x])
df['keywords']=df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
df['cast']=df['cast'].apply(lambda x:[i.replace(" ","") for i in x])
df['crew']=df['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [187]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[Action, Adventure, Fantasy, ScienceFiction]"
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[Adventure, Fantasy, Action]"
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...","[Action, Adventure, Crime]"
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[Action, Crime, Drama, Thriller]"
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...","[Action, Adventure, ScienceFiction]"

In [188]:
df['tags']=df['overview']+df['genres']+df['keywords']+df['cast']+df['crew']

In [189]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...","[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...","[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili..."

In [190]:
new_df=df[['movie_id','title','tags']]

In [191]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
1997,2787,Pitch Black,"[When, their, ship, crash-lands, on, a, remote..."
1998,12658,Someone Like You...,"[Jane, Goodale, has, everything, going, for, h..."
1999,152601,Her,"[In, the, not, so, distant, future,, Theodore,..."
2000,10866,Joy Ride,"[Three, young, people, on, a, road, trip, from..."
2001,227707,The Adventurer: The Curse of the Midas Box,"[17-year-old, Mariah, Mundi's, life, is, turne..."

In [192]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\deboj\AppData\Local\Temp\ipykernel_3796\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [193]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez Action Adventure Fantasy ScienceFiction'

In [194]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\deboj\AppData\Local\Temp\ipykernel_3796\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [195]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [196]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer= WordNetLemmatizer()
def lemma(text):
    y=[]
    for i in text.split():
        y.append(wordnet_lemmatizer.lemmatize(i))
    return " ".join(y)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\deboj\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\deboj\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [197]:
new_df['tags'].apply(lemma)

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bond’s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...
1997    when their ship crash-lands on a remote planet...
1998    jane goodale ha everything going for her. she'...
1999    in the not so distant future, theodore, a lone...
2000    three young people on a road trip from colorad...
2001    17-year-old mariah mundi's life is turned upsi...
Name: tags, Length: 2002, dtype: object

In [198]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1000,stop_words='english')

In [199]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [200]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [201]:
cv.get_feature_names_out()

array(['000', '10', '1970s', '3d', 'accident', 'accidentally', 'act',
       'action', 'adamsandler', 'adoption', 'adventure', 'adventures',
       'africa', 'aftercreditsstinger', 'age', 'agent', 'agrees',
       'airplane', 'airport', 'alecbaldwin', 'alex', 'alice', 'alien',
       'alieninvasion', 'aliens', 'alive', 'america', 'american',
       'ancient', 'andy', 'angeles', 'angelinajolie', 'animal',
       'animation', 'annehathaway', 'anthonyhopkins', 'antoniobanderas',
       'apart', 'apocalyptic', 'armed', 'army', 'arnoldschwarzenegger',
       'arrives', 'art', 'artificialintelligence', 'arts', 'assassin',
       'assassination', 'assigned', 'assignment', 'assistant',
       'astronaut', 'attack', 'attempt', 'attempts', 'attorney', 'author',
       'away', 'baby', 'bad', 'band', 'bank', 'baseball', 'based',
       'basedoncomicbook', 'basedonnovel', 'basedontruestory',
       'basedonvideogame', 'basedonyoungadultnovel', 'basketball',
       'batman', 'battle', 'beach', 'bear', 'beautiful', 'begin',
       'begins', 'believe', 'believes', 'beloved', 'ben', 'benkingsley',
       'benstiller', 'berlin', 'best', 'bestfriend', 'betrayal', 'better',
       'big', 'biggest', 'billionaire', 'biography', 'birthday', 'black',
       'blackmail', 'blood', 'body', 'bomb', 'bond', 'book', 'born',
       'boss', 'boy', 'boyfriend', 'bradpitt', 'break', 'bride', 'bring',
       'brings', 'british', 'brother', 'brotherbrotherrelationship',
       'brothers', 'brothersisterrelationship', 'brucewillis', 'business',
       'businessman', 'california', 'called', 'camerondiaz', 'captain',
       'capture', 'car', 'carchase', 'career', 'case', 'casino', 'cast',
       'castle', 'cat', 'cateblanchett', 'catherinezeta', 'caught',
       'center', 'century', 'chance', 'change', 'changes', 'chaos',
       'characters', 'charlie', 'charlizetheron', 'chase', 'chicago',
       'child', 'childhood', 'children', 'china', 'choice',
       'christianbale', 'christmas', 'church', 'cia', 'circus', 'city',
       'class', 'classic', 'clone', 'close', 'clues', 'coach', 'college',
       'combat', 'come', 'comedy', 'comes', 'community', 'company',
       'competition', 'complete', 'computer', 'connor', 'conspiracy',
       'control', 'cop', 'cops', 'corporate', 'corrupt', 'corruption',
       'country', 'couple', 'courage', 'course', 'court', 'crash',
       'creature', 'creatures', 'crew', 'crime', 'criminal', 'criminals',
       'crisis', 'cross', 'curse', 'dad', 'danger', 'dangerous', 'danny',
       'dark', 'daughter', 'david', 'day', 'days', 'dccomics', 'dead',
       'deadly', 'deal', 'death', 'deception', 'decide', 'decides',
       'deep', 'defeat', 'denzelwashington', 'desert', 'desperate',
       'despite', 'destiny', 'destroy', 'destruction', 'detective',
       'determined', 'different', 'dinosaur', 'director', 'disaster',
       'discover', 'discovers', 'discovery', 'divorce', 'dna', 'doctor',
       'does', 'doesn', 'dog', 'don', 'dr', 'dragon', 'drama', 'dream',
       'dreams', 'drewbarrymore', 'driver', 'drug',
       'duringcreditsstinger', 'dustinhoffman', 'duty', 'dwaynejohnson',
       'dying', 'dyinganddeath', 'dystopia', 'early', 'earth',
       'eccentric', 'eddiemurphy', 'edharris', 'elite', 'elves', 'embark',
       'embarks', 'emperor', 'end', 'ends', 'enemy', 'england', 'english',
       'entire', 'epic', 'escape', 'escapes', 'estranged', 'event',
       'events', 'eventually', 'evil', 'ewanmcgregor', 'ex', 'executive',
       'existence', 'expert', 'explosion', 'extraordinary', 'face',
       'faces', 'fairy', 'fairytale', 'faith', 'fall', 'falls', 'family',
       'famous', 'fantasy', 'far', 'farm', 'fate', 'father',
       'fathersonrelationship', 'fbi', 'fbiagent', 'fear', 'fellow',
       'female', 'fight', 'fighter', 'fighting', 'figure', 'film',
       'final', 'finally', 'finding', 'finds', 'flashback', 'flight',
       'fly', 'flying', 'following', 'follows', 'food', 'football',
       'force', 'forced', 'forces', 'forest', 'forever', 'form',
       'fortune', 'fox', 'framed', 'france', 'frank', 'free', 'freedom',
       'french', 'friend', 'friends', 'friendship', 'funeral', 'future',
       'game', 'games', 'gang', 'gangster', 'garyoldman', 'genehackman',
       'general', 'genius', 'george', 'georgeclooney', 'gerardbutler',
       'gets', 'getting', 'ghost', 'giant', 'gift', 'girl', 'girlfriend',
       'gives', 'global', 'god', 'goes', 'going', 'gold', 'gone', 'good',
       'government', 'great', 'greatest', 'green', 'group', 'growing',
       'grown', 'grows', 'guard', 'gun', 'guy', 'guys', 'hacker', 'half',
       'hands', 'happens', 'happy', 'hard', 'harrisonford', 'harry',
       'having', 'head', 'heads', 'heart', 'heist', 'helicopter', 'hell',
       'help', 'hero', 'heroes', 'heroic', 'hidden', 'high', 'highschool',
       'hired', 'history', 'hit', 'hitman', 'hold', 'holiday',
       'hollywood', 'home', 'honor', 'hope', 'horror', 'horse',
       'hospital', 'hostage', 'hotel', 'house', 'hughjackman', 'human',
       'humanity', 'humans', 'hunt', 'hunter', 'husband', 'ice',
       'identity', 'ii', 'imax', 'important', 'impossible', 'including',
       'incredible', 'independentfilm', 'inside', 'instead',
       'intelligence', 'international', 'inventor', 'investigate',
       'investigation', 'involved', 'island', 'isn', 'jack', 'jackblack',
       'jackson', 'james', 'jamiefoxx', 'jane', 'japan', 'japanese',
       'jasonstatham', 'jealousy', 'jean', 'jenniferlopez', 'jim',
       'jimcarrey', 'jimmy', 'job', 'joe', 'john', 'johnc', 'johncusack',
       'johngoodman', 'johnleguizamo', 'johnmalkovich', 'johnnydepp',
       'johntravolta', 'join', 'joins', 'jones', 'journalist', 'journey',
       'judelaw', 'juliaroberts', 'jungle', 'just', 'justice', 'kate',
       'kevincostner', 'kevinspacey', 'key', 'kidnapped', 'kidnapping',
       'kids', 'kill', 'killed', 'killer', 'killers', 'killing', 'king',
       'kingdom', 'knight', 'know', 'known', 'knows', 'kurtrussell', 'la',
       'land', 'late', 'later', 'latest', 'law', 'lawyer', 'lead',
       'leader', 'leading', 'leads', 'learn', 'learns', 'leave', 'leaves',
       'leaving', 'led', 'lee', 'left', 'legend', 'legendary',
       'leonardodicaprio', 'liamneeson', 'lie', 'life', 'like', 'line',
       'little', 'live', 'lives', 'living', 'll', 'local', 'london',
       'londonengland', 'long', 'look', 'looking', 'lord', 'los',
       'losangeles', 'lost', 'love', 'loveofone', 'lover', 'machine',
       'mafia', 'magic', 'magical', 'major', 'make', 'makes', 'making',
       'man', 'manager', 'manhattan', 'mankind', 'map', 'marine', 'mark',
       'markwahlberg', 'marriage', 'marriagecrisis', 'married', 'marry',
       'mars', 'martialarts', 'marvelcomic', 'massive', 'master', 'match',
       'mattdamon', 'matthewmcconaughey', 'max', 'mayor', 'meet', 'meets',
       'members', 'memory', 'men', 'mentor', 'mercenary', 'merylstreep',
       'met', 'miami', 'michael', 'middle', 'mike', 'military', 'million',
       'mind', 'missing', 'mission', 'mob', 'mobster', 'modern', 'mom',
       'money', 'monkey', 'monster', 'moon', 'morganfreeman', 'mother',
       'mouse', 'moves', 'movie', 'mr', 'murder', 'murdered', 'museum',
       'music', 'musical', 'mutant', 'mysterious', 'mystery', 'named',
       'nation', 'nature', 'navy', 'near', 'need', 'needs', 'neighbor',
       'nemesis', 'neo', 'new', 'newlove', 'news', 'newyork',
       'newyorkcity', 'nick', 'nicolascage', 'nicolekidman', 'night',
       'nightmare', 'north', 'novel', 'nuclear', 'nudity', 'obsession',
       'ocean', 'office', 'officer', 'oil', 'old', 'ontherun',
       'operation', 'operative', 'order', 'ordinary', 'organization',
       'orphan', 'owenwilson', 'owner', 'pair', 'parents', 'paris',
       'park', 'partner', 'partners', 'party', 'passion', 'past', 'paul',
       'peace', 'people', 'perfect', 'person', 'personal', 'peter',
       'pilot', 'pirate', 'place', 'plan', 'plane', 'planet', 'plans',
       'play', 'player', 'playing', 'plot', 'police', 'political',
       'politician', 'politics', 'post', 'power', 'powerful', 'powers',
       'president', 'prevent', 'priest', 'prince', 'princess', 'prison',
       'prisoner', 'problem', 'problems', 'process', 'producer',
       'professor', 'program', 'protect', 'prove', 'psychiatrist', 'puts',
       'queen', 'quest', 'quickly', 'race', 'raised', 'ralphfiennes',
       'rape', 'real', 'reality', 'realize', 'realizes', 'really',
       'rebel', 'recently', 'redemption', 'reilly', 'relationship',
       'reluctant', 'reluctantly', 'remake', 'remote', 'reporter',
       'rescue', 'research', 'resistance', 'rest', 'retirement', 'return',
       'returns', 'reunite', 'revenge', 'rich', 'right', 'ring', 'rise',
       'risk', 'rival', 'rivalry', 'road', 'robbery', 'robert',
       'robertdeniro', 'robertdowneyjr', 'robertduvall', 'robinwilliams',
       'robot', 'rock', 'rogue', 'roman', 'romance', 'romantic',
       'romanticcomedy', 'rule', 'run', 'running', 'runs', 'russellcrowe',
       'russian', 'ruthless', 'ryan', 'safe', 'sam', 'samuell', 'san',
       'sandrabullock', 'sanfrancisco', 'save', 'savingtheworld',
       'scarlettjohansson', 'scheme', 'school', 'science',
       'sciencefiction', 'scientist', 'sea', 'search', 'second', 'secret',
       'secretagent', 'secretidentity', 'secrets', 'security', 'seek',
       'seeking', 'seemingly', 'seen', 'sees', 'self', 'sends', 'sent',
       'sequel', 'sergeant', 'serial', 'serialkiller', 'series',
       'service', 'set', 'sets', 'seven', 'sex', 'shark', 'sheriff',
       'ship', 'shootout', 'shot', 'singer', 'single', 'sister', 'skills',
       'slave', 'slife', 'small', 'sniper', 'snow', 'society', 'soldier',
       'soldiers', 'son', 'soon', 'soul', 'south', 'space', 'spacecraft',
       'spacemarine', 'spaceopera', 'spaceship', 'spacetravel', 'special',
       'spider', 'spirit', 'sport', 'spy', 'stand', 'star', 'stars',
       'start', 'starts', 'state', 'states', 'stay', 'steal',
       'stevebuscemi', 'stevecarell', 'stolen', 'stop', 'storm', 'story',
       'stranded', 'strange', 'street', 'streets', 'struggle',
       'struggles', 'student', 'submarine', 'success', 'successful',
       'suddenly', 'suicide', 'summer', 'sun', 'super', 'superhero',
       'supernatural', 'superpowers', 'survival', 'survive', 'suspense',
       'sylvesterstallone', 'taken', 'takes', 'taking', 'tale', 'target',
       'task', 'teacher', 'team', 'teams', 'tech', 'technology',
       'teenager', 'television', 'tells', 'terrifying', 'terror',
       'terrorism', 'terrorist', 'test', 'texas', 'thief', 'thing',
       'things', 'thinks', 'thought', 'threat', 'threatens', 'thriller',
       'time', 'timetravel', 'tom', 'tomcruise', 'tomhanks',
       'tommyleejones', 'town', 'track', 'tragedy', 'trail', 'train',
       'training', 'trapped', 'travel', 'travels', 'treasure', 'trial',
       'tries', 'trip', 'trouble', 'true', 'truth', 'try', 'trying',
       'turn', 'turned', 'turns', 'tv', 'ultimate', 'ultimately', 'uncle',
       'uncover', 'undercover', 'underworld', 'unexpected',
       'unexpectedly', 'united', 'universe', 'unlikely', 'upside', 'usa',
       'usapresident', 'use', 'uses', 'using', 'vacation', 'vampire',
       'vegas', 'vengeance', 'veteran', 'victim', 'video', 'vigilante',
       'village', 'villain', 'vincevaughn', 'violence', 'violent',
       'virus', 'want', 'wants', 'war', 'warrior', 'washington', 'water',
       'way', 'ways', 'wealthy', 'weapon', 'weapons', 'wedding',
       'werewolf', 'western', 'white', 'widow', 'wife',
       'wifehusbandrelationship', 'wild', 'willferrell', 'willsmith',
       'win', 'winning', 'winter', 'wish', 'witch', 'witness', 'wizard',
       'woman', 'womandirector', 'women', 'woodyharrelson', 'work',
       'worker', 'working', 'works', 'world', 'worldwarii', 'writer',
       'year', 'years', 'york', 'young', 'zombie'], dtype=object)

In [202]:
new_df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley stellanskarsgård chowyun-fat adventure fantasy action"

In [203]:
from sklearn.metrics.pairwise import cosine_similarity

In [204]:
similarity = cosine_similarity(vectors)

In [205]:
similarity[0]

array([1.        , 0.39223227, 0.23570226, ..., 0.20823168, 0.        ,
       0.24948507])

In [206]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:8]
    recommended_movies = []
    for i in movies_list:
        recommended_movies.append(new_df.iloc[i[0]].title)
    return recommended_movies

In [207]:
recommend('The Avengers')

['Iron Man',
 'Avengers: Age of Ultron',
 'Iron Man 3',
 'Captain America: Civil War',
 'Iron Man 2',
 'X-Men',
 'Guardians of the Galaxy']

In [208]:
import pickle
pickle.dump(new_df, open('movies.pkl','wb'))
pickle.dump(similarity, open('similarity.pkl','wb'))